### ISSUE TITLE
Unable to build Maven project using shade plugin

### ISSUE THREAD

**Issue by trisberg** [cloudfoundry/build-system-cnb#4]
The shade plugin renames the original jar as "original-..." and then creates a shaded jar file. This results in two jar files in target dir and the build fails here: https://github.com/cloudfoundry/build-system-buildpack/blob/master/runner/maven.go#L42-L44

"unable to determine built artifact in /workspace/app/target, candidates: [/workspace/app/target/capitalize-java-0.0.1.jar /workspace/app/target/original-capitalize-java-0.0.1.jar]"

This was reported for the projectriff buildpack: https://github.com/projectriff/riff-buildpack/issues/35

**Comment by nebhale** [comment]
Until we've got a large body of evidence that this is an onerous requirement, the buildpack is going to require that `mvn package` be the only command that is run, and the build is required to create a single unambiguous artifact.  If you have requirements beyond that, build in CI and push the deployable binary directly rather than from source.  For Shade, you can [do this](https://stackoverflow.com/questions/50919125/maven-shade-plugin-remove-original).
